feat: dark mode
astoria-tech/meetup pull request #122
Opened 2024-05-14 20:43 UTC by lospoy

Adds:
- basic dark mode

Modifies:
- `useWavyBackground` replaced by:
   - `useWavyBackgroundLight` -> looks better on [/links page](https://lospoy.github.io/meetup/links)
   - `useWavyBackgroundDark` -> looks better on [main feed](https://lospoy.github.io/meetup/)

Staging:
https://lospoy.github.io/meetup/

2024-05-14 20:45 UTC, lospoy commented
@reggi sorry about the commit history, don't understand why the branch has 2 old commits :person_facepalming:

2024-05-15 01:17 UTC, reggi commented
* What do you think about having consistency between home and links? 
* From a design standpoint why would we have two backgrounds? (I'd like to just use the dark one.)
* For the `FeedItem` I like the background and border, I think that should be on links page too. We'd need a shared component for `<Card>`.
* You're implementing darkmode and removing light mode. and not using tailwinds builtins for [dark](https://tailwindcss.com/docs/dark-mode), is there a reason? [See my personal site for example with button to switch between to two](https://reggi.com/).

2024-05-15 19:46 UTC, reggi commented on src/layouts/Card.astro
> +</div>
👋 this is a component not a layout, layouts have like `<html/>` and typically wrap a page.

2024-05-15 19:49 UTC, reggi requested changes
looks good just need to move card to components

2024-05-16 00:54 UTC, reggi approved these changes

2024-05-16 00:54 UTC, reggi commented
Looks great!

2024-05-16 00:55 UTC, merged