refactor: update link colors for contrast
astoria-tech/meetup pull request #129
Opened 2024-05-20 04:24 UTC by ninjaofawesome

## Overview
This PR changes the link colors for contrast as well as a minor fix for the styleguide.  See notes.

## Issue
[ATM-125](https://github.com/astoria-tech/meetup/issues/125)

## Notes
This PR changes the link colors to ones with a 7:1 contrast ratio or higher.  This works on the light or dark themed backgrounds.

Additionally, for readability on the styleguide, for colors, the text is now a white text with a black text stroke color.  See below for an example as well as the new link colors.

## Screenshot
<img width="296" alt="Screen Shot 2024-05-19 at 11 51 35 PM" src="https://github.com/astoria-tech/meetup/assets/3402228/30902885-b16c-4ba2-bc1f-b8e038f5eb0b">

2024-05-20 18:04 UTC, reggi requested changes
added comment above

2024-05-22 05:28 UTC, ninjaofawesome commented
> let me know if i'm missing something here!

At the moment we currently have one theme (just the light one) so what I ended up doing was comparing the background zinc 100 color (#f9f9f9) and the `useWavyBackground` background color (#2d272e) on the WebAIM contrast checker- the base #0944BC color met the contrast criteria for both (it's not my favorite either). 

Could this be an interim step, then have a dark theme added in a separate ticket with different colors entirely for the links?

2024-05-24 05:18 UTC, reggi commented
@ninjaofawesome So we already have darkmode. I was speaking with @lospoy about this is sort of confusing now because we all see the site differently by default. Carlos and I see darkmode because our system settings for our OS are set to use darkmode, I'm guess you don't. I intentionally didn't recognize system settings for my personal website https://reggi.com/, you can set light mode and it will use localstorage to save the setting if you prefer it, but everyone gets darkmode by default to start. Hope this clarifies the original issue and the confusion!

2024-05-24 05:21 UTC, reggi commented
@lospoy ur darkmode implementation doesn't change the background to a lightmode background, so wonky 😆

2024-05-28 03:24 UTC, ninjaofawesome commented
> @ninjaofawesome So we already have darkmode. I was speaking with @lospoy about this is sort of confusing now because we all see the site differently by default. Carlos and I see darkmode because our system settings for our OS are set to use darkmode, I'm guess you don't. I intentionally didn't recognize system settings for my personal website https://reggi.com/, you can set light mode and it will use localstorage to save the setting if you prefer it, but everyone gets darkmode by default to start. Hope this clarifies the original issue and the confusion!

@reggi  TIL!  I prefer dark mode myself, but yeah- prior to the new background I was getting the site in light mode (or so I thought), so I figured that we didn't have a formal one yet.  :)

So- noting the system preferences way of setting dark mode that don't seem to be working correctly here, we could use the [Tailwind way](https://tailwindcss.com/docs/dark-mode) for links here if that works.  If so, is there a preferred color for the links that is preferable?   Or is there a more universal blue color that would work in either mode?

Also learning tons about this, all very cool!

2024-06-12 02:52 UTC, closed without merging

2024-06-12 02:52 UTC, reggi commented
closing out for now